sudo: false
language: php
php:
  - 5.6
  - 7.0
before_script:
  - phpenv versions
  - php -i
  - rm /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - php -i
script:
  - php -v
  - dirname `which php`
  - phpdbg -rr
