dist: trusty
sudo: required
language: php

jobs:
  include:
    - php: 7.4
      dist: bionic
    - php: 7.4
      dist: xenial
    - php: 7.4
      dist: trusty


    - php: 7.3
      dist: bionic
    - php: 7.3
      dist: xenial
    - php: 7.3
      dist: trusty
    - php: 7.3
      dist: precise

    - php: 7.2
      dist: bionic
    - php: 7.2
      dist: xenial
    - php: 7.2
      dist: trusty
    - php: 7.2
      dist: precise

    - php: 7.1
      dist: bionic
    - php: 7.1
      dist: xenial
    - php: 7.1
      dist: trusty
    - php: 7.1
      dist: precise

    - php: 7.0
      dist: xenial
    - php: 7.0
      dist: trusty
    - php: 7.0
      dist: precise

    - php: 5.6
      dist: xenial
    - php: 5.6
      dist: trusty
    - php: 5.6
      dist: precise

    - php: 5.5
      dist: trusty
    - php: 5.5
      dist: precise

    - php: 5.4
      dist: trusty
    - php: 5.4
      dist: precise

    - php: 5.3
      dist: precise

    - php: 5.2
      dist: precise

script: php -v
