dist: xenial
sudo: required
language: php

services:
  - mysql

before_install:
  - sudo mkdir /mnt/ramdisk
  - sudo mount -t tmpfs -o size=1024m tmpfs /mnt/ramdisk
  - sudo service mysql stop
  - sudo mv /var/lib/mysql /mnt/ramdisk
  - sudo ln -s /mnt/ramdisk/mysql /var/lib/mysql
  - sudo service mysql start
