sudo: required
language: php
php:
  - 7.0

addons:
  packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

script:
  - mysql -e 'CREATE DATABASE testdb DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_bin;' ;
  - php test.php
